### ISSUE TITLE
پول ریکوئست فاز منفی دو؟

### ISSUE THREAD

**Issue by mhaghighat20** [shayanro/AP_8#1]
سلام دوستان پس چرا هنوز پول ریکوئست های مربوطه رو نزدین؟
@shayanro @hassanzaker @aliabbasishakh 
اگه توی پول ریکوئست زدن مشکل دارین می تونین لینک زیر رو ببینین:
https://guides.github.com/activities/hello-world/#pr

**Comment by aliabbasi7798** [comment]
ok

**Comment by shayanro** [comment]
Done
